# Generated by Django 5.0.3 on 2024-03-16 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('bio', models.TextField(blank=True, null=True)),
                ('interests', models.TextField(blank=True, null=True)),
                ('specialization', models.CharField(choices=[('Not a specialist', 'Not a specialist'), ('Pharmaceutical Researcher', 'Pharmaceutical Researcher'), ('Clinical Trial Investigator', 'Clinical Trial Investigator'), ('Drug Development Scientist', 'Drug Development Scientist'), ('Regulatory Affairs Specialist', 'Regulatory Affairs Specialist'), ('Medical Writer', 'Medical Writer'), ('Healthcare Professional', 'Healthcare Professional'), ('Pharmacologist', 'Pharmacologist'), ('Biostatistician', 'Biostatistician')], default='Not a specialist', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('affiliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.affiliation')),
            ],
        ),
    ]
