# Generated by Django 5.0.3 on 2024-04-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_alter_clinicaltrial_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
